[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.1"
async-trait = "0.1.86"
chrono = "0.4.39"
repository = { path = "../repository" }
shared = { path = "../shared" }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }
